# Generated by Django 2.2.6 on 2019-10-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191020_0756'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommends',
            field=models.ManyToManyField(blank=True, to='home.Tags'),
        ),
    ]
