# Generated by Django 2.2.6 on 2019-10-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommends',
            field=models.ManyToManyField(to='home.Tags'),
        ),
    ]
