# Generated by Django 2.2.6 on 2019-10-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191020_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='sub', unique=True),
        ),
    ]
