# Generated by Django 2.2.6 on 2019-10-20 13:46

import aspire.home.filerestrict
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('home', '0003_course_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=aspire.home.filerestrict.PdfFileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(upload_to=''),
        ),
        migrations.CreateModel(
            name='ExtraLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
            ],
        ),
    ]
