# Generated by Django 2.2.6 on 2019-10-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191020_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
